### ISSUE TITLE
Art request: Jupiter [Navy battleship]

### ISSUE THREAD

**Issue by finite-galaxy** [finite-galaxy/finite-galaxy#11]
The Republic Navy has four warships, capable of fighting human starships. However, after the Sestor invasion it is clear they need something heavier. Enter the Jupiter battleship:
* 250 engine space and 500 weapon space
* six gun ports on front
* six turret mounts in the middle
* six visible fighter bays on the left
* six visible fighter bays on the right
* a style similar to the Venus [Cruiser] and Saturn [Carrier]

Because I'm not very adept myself at creating images, I'm hoping someone else could design a sprite and thumbnail for the above described starship.

**Comment by theuniverseisfinite** [comment]
![screen shot 2019-01-23 at 8 57 17 pm](https://user-images.githubusercontent.com/46984128/51651670-7ad3f000-1f52-11e9-86f1-a0333029e868.png)
Not that great with blender myself, but I believe i can adequately edit the carrier and cruiser file to produce a stopgap 3d model similar to my _very very_ rough sketch of what i intend it to look like.

**Comment by puzzlecube** [comment]
I got you covered, now about this bad boy!
![jupyter](https://user-images.githubusercontent.com/17504638/51702969-c4681d80-1fda-11e9-813d-3e72440f793b.png)
I did a hi-res version too and have forked this so I could test some parameters. I think I've captured that rough sketch quite well. Do you have any ideas what the other parameters besides 500 weapon space and 250 engine space by any chance?

**Comment by IntegratedQuantum** [comment]
Your design looks good,
but there are 3 problems.
As you can see the saturn contains a detailed texture while your jupiter consists of blank areas.
Also I think (but I'm not sure) you used another lightning (your image seems to be much brighter than the saturn).
As far as I understand it the structures marked in red are the fighter bays, so you should have 12 (instead of 2) of them. It seems like you have mistaken the drone bays(you have 12 of them) for fighter bays.
![saturn](https://user-images.githubusercontent.com/43880493/51704322-0b750380-2019-11e9-9038-6099a1a6d0f7.png)

I don't know what exact parameters @finite-galaxy wants to use, but based on the data he has given and the saturn data I think it would be approximately:
empty mass 1150
shields 26000
hull 11000
drag 28
heat dissipation .3
cargo space 130
outfit space 1250
core space 500

**Comment by puzzlecube** [comment]
Thanks for the feedback and info. Yeah I was afraid you'd say that, I can fix that though easy. As for the blank areas that is before post processing in GIMP just as a POC sprite, On the bright side I have play tested the ship now and it is pretty great and beefy. I will change the fighter bays to be the real deal now.

**Comment by puzzlecube** [comment]
Iteration 2: Still before GIMP, fixed the fighter bays which are HUGE compared to the drone bays. Removed some lights from it too but left a few so you could still see a bit of coloration in the space between the fighter bay wings but the shadows on this monster are tough to tame. Thoughts?
![jupyter_v2 2x](https://user-images.githubusercontent.com/17504638/51715929-56365180-2000-11e9-8687-c71ed066fad8.png)
Also it is not absurdly huge anymore. I some how managed to get the scale horribly wrong.

**Comment by IntegratedQuantum** [comment]
That's better,
but maybe you could give the fighter bay wings a different coloration so that they don't look so similar to each other. They all have the same red coloration.
Have you thought about the turrets? Where will they be placed?
At the moment it appears like you have 2 distinct wings on each sides with 3 fighter bays. How are they related to each other in 3d?

**Comment by puzzlecube** [comment]
I agree the fins on the bays are a bit too constant in their coloration looking at it afterwards. Basically the way the model is set up is that they have small tunnels connecting each set of 3. Perhaps the middle between the bays ought to be beefed up and more decorated. Not sure where the turrets will go exactly. Maybe on the fighter bays or the part between them once I beef it up a bit provided I can get the shadows to not be ridiculous..

**Comment by puzzlecube** [comment]
Try this on for size, Adds a couple ducts that visibly link the bays and changed the color of all but 2 fins slightly to give it some variety. 2 of them even have vertex painted colors. I think maybe the best place for turrets would be on some of the fighter bays, in my play test I had them on the 3 squares at the front of the real fighter bays on the first iteration of the sprite.
![jupyter_v3 2x](https://user-images.githubusercontent.com/17504638/51772129-d74d2180-20b0-11e9-8890-0dc13ca7436c.png)

**Comment by IntegratedQuantum** [comment]
Why did you make 2 of the fins gray?
I think the fins on the rightmost/leftmost fighter bays should either be one continuous fin or separated.

**Comment by puzzlecube** [comment]
2 are gray because I figured it had a lot more color than most human ships compared to the gray except the mercury/gunboat. I can definitely see about separating the outer fins and perhaps making the 2 gray fins a dark reddish color. I have some idea where the turrets could go too now. human ships seem to have no decorative feature that indicates a turret mount.

**Comment by IntegratedQuantum** [comment]
I think you should definitely fill the space between the bays.
It  is perhaps the best protected zone on the entire ship. Any spaceship constructor would add extra outfit space there.

**Comment by puzzlecube** [comment]
I think I have found good spots for the turrets to go. They now sit on small towers coming from the center part that was just added to the sprite. The outermost fins were also modified to have a flatter slope and be less big so the turret mounts could be done in a way that does not look completely ridiculous. Any thoughts? I am also uploading the thumbnail  so you can see more of how things work in 3D (also before postprocessing, those big white octagons will look like they do on the Saturn)
![jupiter 2x](https://user-images.githubusercontent.com/17504638/51806255-6424e600-223d-11e9-8d92-df2718c268bc.png)
![jupiter_thumbnail 2x](https://user-images.githubusercontent.com/17504638/51806260-6dae4e00-223d-11e9-9bad-df0f09281b71.png)

Let me know if the turret mounts or anything looks a bit weird to you, everything looks so much flatter in top down view.

**Comment by finite-galaxy** [comment]
Thank you for your interest! Actually I was hoping for a one-level ship without wings, something more like:
![jupitersketch](https://user-images.githubusercontent.com/44258906/51835405-9ac23580-22fd-11e9-8440-184f81bea545.png)
With blue forward-facing gun ports, green outward-facing fighter bays, red turret mounts, and yellow the engines (as you can see my graphical skills are rather limited).

**Comment by puzzlecube** [comment]
Ah okay, I have completely overhauled the model and now have this.
![new_jupiter 2x](https://user-images.githubusercontent.com/17504638/51864923-a700bf80-230a-11e9-81db-997647f93c92.png)
![new_jupiter_thumbnail 2x](https://user-images.githubusercontent.com/17504638/51865149-28f0e880-230b-11e9-9319-d43052adb556.png)
it.
This ought to have much simpler hardpoints too. Luckily I saved the old version of the model so I can use it later in a plugin.

**Comment by IntegratedQuantum** [comment]
is it just me or are the fighter bays smaller?

**Comment by puzzlecube** [comment]
Done done done and done. Try this one on for size. The fins on the side are quite small but I find them enough to add some color to the extremities.
![jupiter 2x](https://user-images.githubusercontent.com/17504638/51876171-4767db80-232d-11e9-83d1-43f79fa31d53.png)
![jupiter 2x](https://user-images.githubusercontent.com/17504638/51876176-4c2c8f80-232d-11e9-8772-81ff00bea54e.png)

**Comment by finite-galaxy** [comment]
Thanks, that's already much better!
There are still gaps between the bays (white dots), though, so could you fill it up with something? Actually I'd prefer the turret mounts in between where they are right now (red), so the centre of each mount is at the same horizontal position as the centre of the bays on the right and left. Furthermore, it would be nice if you could condense the areas between the front, main body, and aft (cyan), place a few more coloured fins (magenta), and perhaps add secondary engines on the outside (yellow)?
![51864923-a700bf80-230a-11e9-81db-997647f93c92](https://user-images.githubusercontent.com/44258906/51931510-430af380-23fd-11e9-8fab-6dde86c16e4b.png)

**Comment by puzzlecube** [comment]
Ah, not sure why I thought you meant in between fighter bays on the x and y axis rather than just x. Either way try this on for size.
![jupiter 2x](https://user-images.githubusercontent.com/17504638/51950560-99c0ff00-23f6-11e9-9612-aff9fdf1ca20.png)
![jupiter 2x](https://user-images.githubusercontent.com/17504638/51950567-9e85b300-23f6-11e9-8d25-6e4546a30747.png)

I am quite fond of the engine fins, they look cool. The small gaps have been filled in with a tube that sits below the bays, Now that I have uploaded and previewed it I have noticed that the last bit of the fighter bays still have a small gap but it is very close to the white exit part.

**Comment by finite-galaxy** [comment]
Yes, those engine fins are a nice touch, as are the support beams below the bays. It would be nice if you could make those white dots near the bay exits disappear; small horizontal fins at the left and right of the engines might be added too (again, see Venus), but that's not really important either. I'm quite happy with your design already.

To do list:
* design a ship in Blender (about finished)
* do post-processing in GIMP (roughen up the surface, open the bays), e.g.:
![saturn 2x](https://user-images.githubusercontent.com/44258906/51972931-d8999800-247c-11e9-99ce-920081fccf7b.png)
* make a pull request here on github to add the images and insert yourself in the copyright file

**Comment by finite-galaxy** [comment]
#31 is merged in a149c9d86bfc5235a8ab1cc62f9a21ecb908622c

**Comment by finite-galaxy** [comment]
Maybe I should scaled it down a bit, the World-Ship now looks quite small:
![screenshot from 2019-02-08 13-40-55](https://user-images.githubusercontent.com/44258906/52479247-498d2e00-2ba8-11e9-95fc-d21010eee4f1.png)
