### ISSUE TITLE
Navigation Map Bug

### ISSUE THREAD

**Issue by IntegratedQuantum** [finite-galaxy/finite-galaxy#12]
Your new fuel system is a very good idea, but it creates a bug.
If you open the map and have a route selected then the map displays the maximum travel distance with current fuel amount and total mass.
If landed the map shows only the maximum travel distance without any cargo or mission cargo(even if cargo is loaded).

**Comment by finite-galaxy** [comment]
Thank you for pointing this out. If I understand correctly, you're saying:
* when in space, the route colouring uses effective mass, including cargo and fighters
* when on a planet, the route colouring uses empty mass, ignoring cargo and fighters

I agree this is misleading and should be fixed. I'll have a look at the code to see if there is an easy way to correct this.

However, my initial guess is this is actually a different issue: cargo is only distributed upon departure. E.g., if you have two Star Barges your fleet cargo space is 100, which means you can purchase a Fusion Reactor; if you depart, the reactor will suddenly disappear and both your ships will be empty, because neither has enough space to accomodate it.

**Comment by IntegratedQuantum** [comment]
> I agree this is misleading and should be fixed. I'll have a look at the code to see if there is an easy way to correct this.

I think the easiest way to fix this would be precalculating the ships mass every time the map is opened.

**Comment by finite-galaxy** [comment]
> I think the easiest way to fix this would be precalculating the ships mass every time the map is opened.

`void MapPanel::DrawTravelPlan()` is the function that colours the routes; `double Ship::BestFuel(const string &type, const string &subtype) const` calculates the effective jump fuel, which uses the ship's actual mass.

> Also i'm not quite sure about your "invalid" label. Does it mean the problem I describe doesn't seem right or the Issue report itself doesn't seem right?

Neither: it means something in the game doesn't seem right. (As opposed to a bug, which means that something doesn't work.) Feel free to suggest a better name for this label; I agree “invalid” might be confusing,

**Comment by IntegratedQuantum** [comment]
> Neither: it means something in the game doesn't seem right. (As opposed to a bug, which means that something doesn't work.) Feel free to suggest a better name for this label; I agree “invalid” might be confusing,

How about simply using "problem"? With this you can still define the same kind of issues(the general mechanic does work, but there is a problem about it) while a bug would be the extreme case(the described mechanic doesn't work)

**Comment by finite-galaxy** [comment]
Thank you for your contribution!

If I understand correctly, cargo is now taken into account when your ship is on a planet, but fighters are ignored. (There are included when in flight.) To do: check if that's true.
