### ISSUE TITLE
Fonts size issue

### ISSUE THREAD

**Issue by Sagez** [finite-galaxy/finite-galaxy#41]
Hello, I have some issue with font on finite galaxy. is there way to use system font than using default font of yours.
I am using Archlinux. Beside I tried with regular endless sky it work flawless without any issue with font.

![Font Size issue 1](https://user-images.githubusercontent.com/40505773/71644851-d47d8800-2c94-11ea-9ead-489fe8052a49.png)
![Font Size issue 2](https://user-images.githubusercontent.com/40505773/71644852-d47d8800-2c94-11ea-99c4-88f58eab76fd.png)

**Comment by finite-galaxy** [comment]
Thank you for reporting this!
The issue seems to be the other way around: the game is supposed to use the game font (Linux Libertine Display), but on your end it appears to use your system font instead (which is wider). This is how it look likes at my end:
![Screenshot from 2020-01-07 10-46-17](https://user-images.githubusercontent.com/44258906/71885707-2dd53380-313b-11ea-9ac4-e2b0eeece6eb.png)
> Beside I tried with regular endless sky it work flawless without any issue with font.
The reason for that is that Endless Sky does not use font files (.otf/.ttf); it has two png images with a limited number of signs; text strings are split into individual characters, which correspond to a location on the png, which is then displayed in the game.
What I changed with respect to ES is that I incorporated https://github.com/endless-sky/endless-sky/pull/3312, so the game use font files and can support Unicode characters, amongst other things.

Now as to how to solve the wrong font of you. 
One explanation I could think of is that the game ignores the fonts/* file it has and searches for installed fonts; if it can't find them on your computer, then it defaults to your system font. To solve that, try installing the Linux Libertine fonts and see if it solves the problem. The official site is http://libertine-fonts.org/, but you can get them from other locations as well and it's probably available in font managers or as a separate package (perhaps `ttf-linux-libertine`).
If that doesn't work, then perhaps the problem is that some dependency is missing, perhaps `pango` or `cairo`. Hopefully installing that (and recompiling finite-galaxy) will solve it.

Could you try the above and report back? There are probably other people experiencing the same issue.

**Comment by stacy-rendall** [comment]
I can confirm that installing `ttf-linux-libertine` fixed this issue for me on an Arch based distro (Manjaro with Gnome)

**Comment by Sagez** [comment]
thanks for note stacy-rendall that helps.
